# Generated by Django 4.1 on 2023-03-24 13:16

from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('name', models.CharField(default='No Title', max_length=1000)),
                ('picture', models.ImageField(default='supplier-pics/default_pic.gif', null=True, upload_to=product.models.supplier_image_upload_handler)),
                ('city', models.CharField(default='No Title', max_length=100)),
                ('description', models.CharField(default='No Title', max_length=1000)),
                ('rating', models.IntegerField(default=100, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(default='No Title', max_length=1000)),
                ('price', models.CharField(default='', max_length=10000)),
                ('category', models.CharField(default='Undefined', max_length=10000)),
                ('description', models.CharField(default=None, max_length=10000)),
                ('picture', models.ImageField(default='product-pics/default_pic.gif', null=True, upload_to=product.models.product_image_upload_handler)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.supplier')),
            ],
        ),
    ]
