# Generated by Django 4.1 on 2023-04-23 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_category_subcategory_alter_replycomment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
