# Generated by Django 4.1 on 2023-04-23 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_category_subcategory_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='oldPrice',
        ),
    ]
