# Generated by Django 4.1 on 2023-04-27 10:47

from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_category_product_oldprice_subcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PictureList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture1', models.ImageField(default='product-pics/default_pic.gif', null=True, upload_to=product.models.product_image_upload_handler)),
                ('picture2', models.ImageField(default='product-pics/default_pic.gif', null=True, upload_to=product.models.product_image_upload_handler)),
                ('picture3', models.ImageField(default='product-pics/default_pic.gif', null=True, upload_to=product.models.product_image_upload_handler)),
                ('picture4', models.ImageField(default='product-pics/default_pic.gif', null=True, upload_to=product.models.product_image_upload_handler)),
                ('picture5', models.ImageField(default='product-pics/default_pic.gif', null=True, upload_to=product.models.product_image_upload_handler)),
                ('picture6', models.ImageField(default='product-pics/default_pic.gif', null=True, upload_to=product.models.product_image_upload_handler)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'verbose_name_plural': 'Picture List',
            },
        ),
    ]
