# Generated by Django 4.1 on 2023-04-27 11:08

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_picturelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(default='product-pics/default_pic.png', null=True, upload_to=product.models.product_image_upload_handler),
        ),
    ]
