# Generated by Django 4.1 on 2023-05-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='overall',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=10),
        ),
    ]
