# Generated by Django 4.1 on 2023-05-18 09:41

from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_alter_order_complete_alter_order_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picturelist',
            name='picture1',
            field=models.ImageField(default=None, null=True, upload_to=product.models.product_image_upload_handler),
        ),
        migrations.AlterField(
            model_name='picturelist',
            name='picture2',
            field=models.ImageField(default=None, null=True, upload_to=product.models.product_image_upload_handler),
        ),
        migrations.AlterField(
            model_name='picturelist',
            name='picture3',
            field=models.ImageField(default=None, null=True, upload_to=product.models.product_image_upload_handler),
        ),
        migrations.AlterField(
            model_name='picturelist',
            name='picture4',
            field=models.ImageField(default=None, null=True, upload_to=product.models.product_image_upload_handler),
        ),
        migrations.AlterField(
            model_name='picturelist',
            name='picture5',
            field=models.ImageField(default=None, null=True, upload_to=product.models.product_image_upload_handler),
        ),
        migrations.AlterField(
            model_name='picturelist',
            name='picture6',
            field=models.ImageField(default=None, null=True, upload_to=product.models.product_image_upload_handler),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.subcategory'),
        ),
    ]
